name: Generate GitHub Stats Images

on:
  schedule:
    - cron: '30 0 * * *'   # roda toda noite às 00:30 (UTC)
  workflow_dispatch:        # permite rodar manualmente pela aba Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate images
        uses: jstrieb/github-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
